apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: hanoguz00/fastapi-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: "postgresql://postgres:postgres@postgres.test.svc.cluster.local/postgres"
